### ISSUE TITLE
High DPI drawing

### ISSUE THREAD

**Issue by getzen** [Nazariglez/notan#100]
It seems that Notan provides a high dpi window. For example ,on my iMac there are 2x as many physical pixels as logical pixels, which is great. However, the drawing shapes and text appears to be in normal/logical pixels, making them look low-res, so to speak. Placing shapes/text with logical coordinates is fine, but the _appearance_ doesn't seem to be high dpi. Is this correct and intended? Is there a way to "turn on" high dpi drawing?

One workaround, as least for text, seems to be drawing at twice the needed font size and applying a scale of 0.5. That's very awkward though, and messes up the positioning.

I know dpi matters can get complicated, but I'm trying to understand Notan's approach.

**Comment by Nazariglez** [comment]
This is one of those things that I did not think about just yet. 

Notan will adapt the viewport to avoid the hassle of different DPIs, but I have done nothing with the drawing API. Probably I could try to add a HighDPI mode to the `draw` API which adapts the shapes and text to the device DPI, not sure how it will interact with the transformation system, so I need to do some tests.

 However, I am open to suggestions, what do you think will be a good approach?

**Comment by Nazariglez** [comment]
There is another option, disable the HighDPI https://github.com/Nazariglez/notan/blob/develop/crates/notan_winit/src/window.rs#L95. Not sure how it will looks, right now it doesn't work because winit is not applying correctly this (I checked the code there diagonally). I will fix and sent a PR but I am not sure if this is what you're looking for. 

Related: 
* https://github.com/panda3d/panda3d/issues/794
* https://github.com/libsdl-org/SDL/commit/009226c61e4637c57d5e0bea3ca86866da5651fb
* https://github.com/godotengine/godot/pull/32809/files

**Comment by getzen** [comment]
I'm no expert in these matters, but one approach is for high dpi drawing to be used _automatically_ when in a high dpi environment. That way, it's transparent to the user. I believe this is how Macroquad handles it.

Of course, when it comes to texture clarity, the user will still need to provide 2x-sized textures and scale them down.

**Comment by Nazariglez** [comment]
I think that I'm going to do this in three steps: 

* Fix `high_dpi` feature on winit -> https://github.com/rust-windowing/winit/pull/2339 
* Disable `high_dpi` on notan by default and let the user enable it if they want. (This seems to be the behavior in other engines/frameworks)
* Adapt the Draw2D API to use HighDPI sizes 

Let's keep this issue open for now.

**Comment by getzen** [comment]
Thank you for working on it!

**Comment by Nazariglez** [comment]
Pinning this blocker here to be able to check it without find in the winit repository: https://github.com/rust-windowing/winit/pull/2322

**Comment by Nazariglez** [comment]
Half of this is already done: #122 
I still need to think of a good way to draw easily:
* Using primitives (viewport can adapt, this is already working)
* Draw2d  high dpi shapes (transformation matrix should work as usual).
* Draw2d high dpi images (transformation matrix should work as usual). 

I am thinking about adding a `.resolution(n: f32)` when creating an image, to indicate its resolution, and if the image is created the default image load I can use the suffix on the image's name (@2x.png) to set the resolution automatically. 

Though this should have a way to disable it in case the user wants to manage High DPI in their own way, I may add to the `Draw` object a way to set resolution, maybe also to the `Renderer` object.

All of this is me just thinking loud.
