### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by mensch272** [Nazariglez/notan#117]
It is widely accepted that Vulkan performs better than OpenGL (currently used).

I want to enquire about whether Vulkan will be supported.

**Comment by Nazariglez** [comment]
Hi!

It will happen eventually, probably using [WGPU](https://wgpu.rs/) (it supports vulkan) which seems to be the go-to way for the rust community. 

Said that I think that the numbers of notan are really good for most cases, even using OpenGL. And there is still room for improvements in performance. 

I gladly will review and accept a WGPU/Vulkan PR. Do you have experience using wgpu? Will you like to help us to add support for it?

**Comment by mensch272** [comment]
The performance is good for my usage too, yes.

Sadly I have no experience with WGPU, but I might create a pull request when and If I get to learn it.

Thanks for the quick response.

**Comment by Nazariglez** [comment]
I hope to have something about wgpu (at least experiment a bit with it) soon. I am closing this but feel free to open it again if you want.
