### ISSUE TITLE
Add builder methods that take values to WindowConfig

### ISSUE THREAD

**Issue by mensch272** [Nazariglez/notan#118]
I noticed that the following methods do not have variants that take values as arguments.

![Screenshot_20220730_193509](https://user-images.githubusercontent.com/47662901/181919181-59992d69-3d46-4967-b972-710e30f3c49d.png)

I was expecting to be allowed to do:

```rust
let window_config = WindowConfig::new()
    .title("Lament")
    .size(1280, 720)
    .vsync(true)
    .resizable(true);
```

I believe this is much more clear. The alternative currently is to:

```rust
let window_config = WindowConfig {
    title: String::from("Lament"),
    width: 1280,
    height: 720,
    vsync: true,
    resizable: true,
    ..Default::default()
};
```

**Comment by Nazariglez** [comment]
This makes sense to me, I'll add it for the next release. Thanks!
