### ISSUE TITLE
Example `game_15_puzzle` generates invalid arrangements

### ISSUE THREAD

**Issue by taotao54321** [Nazariglez/notan#124]
version: commit 6fe050671ec3ac1a04ec7517ab3a39250a44bfc5

Example `game_15_puzzle` generates invalid arrangements. For example, this board has two 10:

![invalid-15puzzle](https://user-images.githubusercontent.com/21364118/184937849-b60715a4-bb93-4ee5-959e-df96627b675f.png)

The problem will be this code:

https://github.com/Nazariglez/notan/blob/6fe050671ec3ac1a04ec7517ab3a39250a44bfc5/examples/game_15_puzzle.rs#L205-L211

`(NUMBERS - 1)` will be wrong. This should be `NUMBERS`.

Moreover, there is a 1/2 chance of generating [unsolvable arrangements](https://en.wikipedia.org/wiki/15_puzzle#Solvability). This example simply shuffles numbers, but it will have to consider a parity.

**Comment by Nazariglez** [comment]
Hey nice catch! 

Thank you so much for take the time to test and spot the error. Will you be comfortable doing a PR with the fix?

**Comment by taotao54321** [comment]
Okay, I made a PR.
