### ISSUE TITLE
Problem with transparency in textures

### ISSUE THREAD

**Issue by dmvict** [Nazariglez/notan#127]
I'd tried to make scene with several textures with different positions on axis Z. 
All textures are the PNG files with transparent background. 

The problem is that textures transparency does not work properly. It is the nearest texture on axis Z overrides another textures. 
Here is the screenshot of the effect, the rectangles on the screenshot added to show edges of the textures
![image](https://user-images.githubusercontent.com/47529590/186334293-a64a99a5-c12e-4503-ad4d-60ddd2e99153.png)
As screenshot shows that the texture with Etherium icon  ( black rectangle ) overrides another texture. 

What I tried to do: 
- use all variants of `depth_stensil` in pipeline setup;
- use all variants of `depth_stensil` in ClearOptions;
- use all constant variants of alpha blending in pipeline setup;
- use all constant variants of color blending in pipeline setup;
- mix settings.

[Here is the minimal example to reproduce the problem](https://github.com/Wandalen/notan_opacity_problem.git). To run the example, use the instructions in README. 

What work for me, and what I want to do not use: disable `depth_stensil` and sort textures manually.
It is the screeshot of the example with disabled `depth_stensil`:
![image](https://user-images.githubusercontent.com/47529590/186336255-d2d89d90-fb69-45c9-a3a6-717e4127fe7c.png)
The transparent areas of textures do not override another textures, but depth sorting disabled.

**Comment by Nazariglez** [comment]
I see, let me do some tests and I'll come back. I don't discard that something is wrong with how the commands are translated to GL.

**Comment by Nazariglez** [comment]
It seems that sort of transparencies/opaque draws are a pretty tricky topic. More info [here](https://learnopengl.com/Advanced-OpenGL/Blending).

But a pretty easy trick to fix this and get the behavior you want is just discarding transparent pixels on the fragment shader. 

```
    vec4 texColor = texture( u_texture, v_uv );
    if (texColor.a <= 0.0) discard;
    color = texColor;
``` 

Let me know if it works.

**Comment by dmvict** [comment]
> 

Hello, @Nazariglez 

Yes, this solution works well. I enabled sorting with `depth_sorting`, and all textures were drawn as expected.
