### ISSUE TITLE
Window: Set always on top

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#129]
`Winit` has a method to set a window as "Always on top": https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_always_on_top

Would it make sense to expose this functionality inside `notan` as well? For multimedia apps this might be a useful feature.

**Comment by Nazariglez** [comment]
Hello! 

It makes sense to me, it seems that also SDL2 and GLFW also support this so if somebody wants to create another backend with them the option is still there. 

My main worry is how this should behave on web browsers, maybe just `no-op`? I don't see either a clear use for it on the web. 

What do you think?

**Comment by woelper** [comment]
Thanks so much for your answer! I fully agree with your thoughts on the web - I think this  only useful in a desktop context and has no use on the web.

**Comment by Nazariglez** [comment]
> Thanks so much for your answer! I fully agree with your thoughts on the web - I think this is only useful in a desktop context and has no use on the web.

Anytime!

I can do this. However is an easy change, how do you feel about sending a PR with it? It could be similar to this https://github.com/Nazariglez/notan/commit/1c96c5c52a04be6d6d5e71b70bc28be3f647e69f, avoiding the web backend and also passing `true/false` on the `WindowConfig` like this: https://github.com/Nazariglez/notan/commit/0af6b7ebe03284ef3faa6490bf2b55bce9f7f47b

Let me know if feel like trying it!

**Comment by woelper** [comment]
Thanks! Yes, absolutely, I am happy to try that out! I'll let you know if I have something (or questions, if that's fine)!

Thanks!

**Comment by woelper** [comment]
Hi @Nazariglez ,
I started a PR here:
https://github.com/Nazariglez/notan/pull/132

I am unsure about the `empty.rs` - your feedback is greatly appreciated. Would you like me to add an example as well?

**Comment by Nazariglez** [comment]
It looks good to me, `empty` is just a mockup of the backend, some dummy thing to use in case no backend is present. I think that we don't need an example for this, but if you want we can add it of course.

Already merged, thanks!
