### ISSUE TITLE
discord server

### ISSUE THREAD

**Issue by yzn-h** [Nazariglez/notan#137]
it will be nice if there is a discord server for notan

i made one:
https://discord.gg/rH3nP7neeu

**Comment by Nazariglez** [comment]
I don't use discord too much, but this it's a great idea, I miss sometimes a place just to chat and ask people about changes or things they need. Thanks!

I am trying to accept the invitation, but I always get a message that I cannot accept the invitation and the logs display a 401 error.

**Comment by yzn-h** [comment]
strange try to accept it from your phone i made n dummy account and it works

**Comment by Nazariglez** [comment]
Done! Thanks 

Should we added it to the github page? or readme?

**Comment by yzn-h** [comment]
yes please
and i gave you admin role in the server

**Comment by Nazariglez** [comment]
Added to the readme!
