### ISSUE TITLE
[Question/Enhancement] Are different backends coming soon?

### ISSUE THREAD

**Issue by coder3112** [Nazariglez/notan#141]
I remember you mentioning on [Reddit](https://www.reddit.com/r/rust/comments/tpt17m/comment/i2f7zdr/?utm_source=share&utm_medium=web2x&context=3) that you plan to add support for more backends in the future. 

Are you planning on doing this soon? I have been looking to learn more rust by contributing to some libraries and this seems like a good place to start for that as well.

**Comment by coder3112** [comment]
Sorry if this question is misinformed or something, I am just quite new to the project and quite interested. My (admittedly little) research yielded nothing special though.

**Comment by Nazariglez** [comment]
Welcome @coder3112 ! Yes, we still want to add new backends, mainly WGPU for the graphics, and make the current backends (or new ones) work with android and ios. 

Do you have any experience with any of these platforms or APIs? Any help with it will be great.

**Comment by coder3112** [comment]
That is nice to hear! I am all for FOSS competition, and different manifestations of the same concept but in different forms.

As I said, I am still learning. While I am certainly not good enough to contribute today, I still think I could make a private fork and learn about a backend such as WGPU and try to implement it here. Eventually, I might be able to contribute here. That is still far off though...

In the meantime, I hope to familiarise myself with the library and maybe submit some PRs for Bug fixes/typos, etc.

**Comment by Nazariglez** [comment]
Of course, and don't feel that you should be contributing back just because you are using it, it will be nice, but it's more than enough if you report any weird thing you see while you use the lib!

Thanks!

PD: I am closing the issue but feel free to keep posting here or open a new one if you need to.
