### ISSUE TITLE
EGUI text does not look sharp using light theme on browsers

### ISSUE THREAD

**Issue by UE2020** [Nazariglez/notan#158]
egui text looks blocky and generally unreadable in WebGL (especially in light mode, less so in dark mode). A comparison is attached below.

native: https://i.imgur.com/dpZgcZS.png
web: https://i.imgur.com/hqVo4m0.png (taken in the [web demo](https://nazariglez.github.io/notan-web/examples/egui_demo.html))

**Comment by Nazariglez** [comment]
Thanks for the report, I'll take a look to it!

**Comment by Nazariglez** [comment]
This must be fixed using the latest changes on the develop branch, It will be soon out on crates.io. 

Feel free to reopen if something feels odd.
