### ISSUE TITLE
Uneeded warning? (recursing into entrypoint `main`)

### ISSUE THREAD

**Issue by danny-burrows** [Nazariglez/notan#159]
Hi there, this is rather a minor issue but just one of slight annoyance for those of us trying to clear up `cargo clippy` warnings. This pops up when `#[notan_main]` is applied to my main function...

```bash
~$ cargo clippy
warning: recursing into entrypoint `main`
  --> src/main.rs:__:__
   |
31 | fn main() -> Result<(), String> {
   |    ^^^^
   |
   = note: `#[warn(clippy::main_recursion)]` on by default
   = help: consider using another function for this recursion
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#main_recursion
```

I just wondered if there was a way we could remedy this?

I have tried putting a `#[allow(clippy::main_recursion)]` before and after `#[notan_main]` but to no avail.

Just wondered if anyone could help, if we find a good solution I could open some kind of PR?

**Edit:** I have found a solution and opened a [PR](https://github.com/Nazariglez/notan/pull/160)

**Comment by Nazariglez** [comment]
Closing it, thanks for the PR!
