### ISSUE TITLE
Use different types of index buffers with Pipelines

### ISSUE THREAD

**Issue by jawadsh123** [Nazariglez/notan#163]
right now index buffer type is pinned to `glow::UNSIGNED_INT`
https://github.com/Nazariglez/notan/blob/f2cc8397fe783ef2553aeb09f40d89402d412f86/crates/notan_glow/src/lib.rs#L342-L343

I'm working with a lib that gives me back u16 buffers, which I then have to _upgrade_ to u32 causing an extra copy!
would be nice to be able to upload them directly

do you feel this should be supported?
if yes, in terms of API I'm thinking there could be a `with_info` on `IndexBufferBuilder` and a `IndexFormat` enum that captures all the types, wdyt?

**Comment by Nazariglez** [comment]
It's a great idea. It sounds good to me. 

I have a work-in-progress PR... I am not sure if it works quite right in all the situations, and I am not sure either about the API. It works just by passing a `&[u16]` or `&[u32]` to `.with_data(&[T])`. I am trying to avoid setting the format manually. 

The main downside is that the user needs to specify the type of buffer before passing it, if not a compiler error will tell the user that the type passed doesn't implement the trait required, which is quite an ugly error message. 

So:
```
let index = [0, 1, 2, 3, 4]; // this doesn't work
let index = [0u16, 1, 2, 3, 4]; // this does it
```

So I am thinking about adding a different method for `u16` buffers, like `.with_data_u16(&[u16])` keeping the `.with_data(&[u32])` that we have now. 

Anyway, let me know what do you think about the PR, if it is what you were looking for or if you see something wrong.

**Comment by Nazariglez** [comment]
I did the change. Now you can use `.with_data_u16` for `u16` and `.with_data` for `u32`.

The format will be inferred by the method used to set the data, but if you are initializing the buffer without data you can set the format with `.with_format(IndexFormat::Uint16)`.
