### ISSUE TITLE
Fullscreen doesn't work using Linux Mint and the Winit backend.

### ISSUE THREAD

**Issue by LedinecMing** [Nazariglez/notan#167]
![image](https://user-images.githubusercontent.com/63245550/196227389-a5e4de1f-f28b-4d2e-818e-51e58d25c049.png)
sys: linux mint cinnamon 21
![image](https://user-images.githubusercontent.com/63245550/196227604-baf0771c-6e10-436c-a0dc-bcee8c4edf4f.png)

**Comment by Nazariglez** [comment]
Hello! I do think that's because of the `.max_size(W, H)`.

**Comment by LedinecMing** [comment]
Mu .max_size dont work with it also, it seems to be strange if not documented

**Comment by Nazariglez** [comment]
I cannot reproduce it, but this must be a winit issue, we do nothing related to the fullscreen or window management, we have only a thin wrapper on top of it. 

Can you open a [issue there](https://github.com/rust-windowing/winit/issues)?

Thanks!

**Comment by LedinecMing** [comment]
That seems to be fixed, good.
