### ISSUE TITLE
Text render issue(?)

### ISSUE THREAD

**Issue by LedinecMing** [Nazariglez/notan#169]
Text with upper signs (á) does not render
Is this an issue or works as supposed?

**Comment by LedinecMing** [comment]
P.s: upper signs are rendered as a []

**Comment by Nazariglez** [comment]
It depends on the font you're using. 

For example, using "Ubuntu-B.ttf":
```
    draw.text(&font, "áéíóú àèìòù äëïöü ç âêîôû")
        .position(400.0, 300.0)
        .size(40.0)
        .color(Color::ORANGE)
        .h_align_center()
        .v_align_middle();
```

<img width="536" alt="Screenshot 2022-10-19 at 19 50 19" src="https://user-images.githubusercontent.com/1929191/196778935-957f57d7-b80e-424a-8389-05e59e21c32e.png">
