### ISSUE TITLE
Very slow scrolling in egui combo boxes

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#203]
When using a `ComboBox`, the scrolling speed is extremely slow - to a point where dragging the slider with the mouse is the only option. I have verified this with standalone  egui and this seems to only happen in the notan integration.

This is an example building upon the `egui_basic` example:

```rust
use notan::egui::{self, *};
use notan::prelude::*;

#[notan_main]
fn main() -> Result<(), String> {
    let win = WindowConfig::new()
        .vsync(true)
        .lazy_loop(true)
        .high_dpi(true);

    notan::init()
        .add_config(win)
        .add_config(EguiConfig)
        .draw(draw)
        .build()
}

fn draw(app: &mut App, gfx: &mut Graphics, plugins: &mut Plugins) {
    let mut output = plugins.egui(|ctx| {
        egui::SidePanel::left("side_panel").show(&ctx, |ui| {
            ui.heading("Egui Plugin Example");

            ui.separator();
            if ui.button("Quit").clicked() {
                app.exit();
            }

            let mut selected = 1;
            egui::ComboBox::from_id_source("Imageops")
            .show_ui(ui, |ui| {
                for i in 0..100 {
                    ui.selectable_value(&mut selected, i, format!(" item{i}"));
                }
            });

            ui.separator();
            ui.label("Welcome to a basic example of how to use Egui with notan.");

            ui.separator();
            ui.label("Check the source code to learn more about how it works");
        });
    });

    output.clear_color(Color::BLACK);

    if output.needs_repaint() {
        gfx.render(&output);
    }
}

```

**Comment by Nazariglez** [comment]
It's probably something related to my implementation, I'll check it, thanks!

**Comment by riverfr0zen** [comment]
I've noticed this is not limited to ComboBox. I get the same issue with a ScrollArea too.

**Comment by Olaroll** [comment]
I'd also be interested in seeing this fixed. The problem seems to arise from how notan uses number of lines for scroll height, but egui expects pixels. I'll leave useful links that might help in solving this.

The issue can probably be fixed in one of these locations:
notan window scroll event handling: https://github.com/Nazariglez/notan/blob/d3230a5/crates/notan_winit/src/mouse.rs#L31
notan forwarding scroll to egui: https://github.com/Nazariglez/notan/blob/c7d240c/crates/notan_egui/src/plugin.rs#L188

And these might help decide on how to fix it:
How eframe handles scroll on native: https://github.com/emilk/egui/blob/7215fdf/crates/egui-winit/src/lib.rs#L551
How eframe handles scroll on wasm: https://github.com/emilk/egui/blob/7215fdf/crates/eframe/src/web/events.rs#L405

**Comment by Nazariglez** [comment]
This is great, I am planning to take a deep look to the egui integration for next version, and this must be fixed for sure there. I hope to have something working on the `breaking` or `develop` branch in the next weeks. 

Thank you all for the information, and thanks @Olaroll for debugging and looking the internals to give me some hints where to look.

**Comment by Nazariglez** [comment]
This is already fixed on #256 although it will take a "while" before it's merged to develop. Also, develop is a breaking branch, so if this is important for you now and don't want to wait/address breaking changes in the next weeks, we can plan to release `0.9.5` whit this change. What do you think? 

Thank you everybody for the work here.

**Comment by woelper** [comment]
Thank you so much, this is absolutely great!
I don't mind waiting, but if this is something you feel good about to release in `0.9.5` I would be happy - whatever is most convenient for you!

**Comment by woelper** [comment]
Just a comment: First of all, thanks for fixing this!
I noticed that zoom speed seems to have increased. I do get a `+50`/ `-50` delta on mouse wheel scroll now as a notan event, and also touchpad scrolling seem faster. This is not an issue (I am dividing by 10 and min/maxing the amount) but maybe this is something that happened as side effect.
