### ISSUE TITLE
SHORT audio messed up [wav]

### ISSUE THREAD

**Issue by duckfromdiscord** [Nazariglez/notan#206]
sounds play at the wrong speed 

https://cdn.discordapp.com/attachments/1020682761490681878/1065695989417128027/glitch.mp3

1st is correct, 2nd is what is played by notan. if i add silence at the beginning and the end of the original wav file, the sound is obviously delayed but it is not sped up.

**Comment by Nazariglez** [comment]
Hello @duckfromdiscord, do you have the original file so I can try to test and fix it? Thanks

**Comment by duckfromdiscord** [comment]
@Nazariglez 
[pause.zip](https://github.com/Nazariglez/notan/files/10472337/pause.zip)
GitHub will not allow me to upload .wav so I put it in a .zip

**Comment by Nazariglez** [comment]
Thanks! I'll check this probably this week.

**Comment by Nazariglez** [comment]
This is quite interesting, I can hear the sound different when it's played by notan, by vlc and by audacity. Same file, three different sounds...

I need to keep investigating this, thanks for the heads up.

**Comment by Nazariglez** [comment]
Hahaha I thought I put more time to trigger it, I need to recheck it and maybe increase it even more.

**Comment by duckfromdiscord** [comment]
Awesome! Is this tested ?

**Comment by Nazariglez** [comment]
I tried with the same audio file you gave to me on web and macos, it seems to be working fine, let me know if you see something weird!
