### ISSUE TITLE
Docs.rs won't build

### ISSUE THREAD

**Issue by midnadimple** [Nazariglez/notan#211]
For the past 2 releases, the docs on https://docs.rs/notan have failed to build. I tested the build locally on Ubuntu Unity 22.10, and they built fine. Build logs can be found here: [0.9.0](https://docs.rs/crate/notan/0.9.0/builds/727944), [0.8.0](https://docs.rs/crate/notan/0.8.0/builds/687707).

**Comment by Nazariglez** [comment]
Ugh, I thought I fixed this making `--all-features` works again (https://github.com/Nazariglez/notan/commit/283422376933b297468a6713a632ea0b37adbf1a). I guess that `shaderc` is a _no go_ for docs, so I will change how the doc generation works excluding it. 

Thanks for the heads up @midnadimple !

**Comment by Nazariglez** [comment]
Should be fixed now! thanks

**Comment by midnadimple** [comment]
np mam
