### ISSUE TITLE
Panic when using default `egui::FontDefinitions`

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#216]
I tried using a custom `FontDefinitions` without inserting a custom font and this led to a panic:

```
notan_app::graphics] Failed to find EGUI texture Managed(0)
thread 'main' panicked at 'Failed to find EGUI texture Managed(0)', /home/woelper/.cargo/registry/src/github.com-1ecc6299db9ec823/notan_app-0.9.1/src/graphics.rs:121:13
```

I tried doing the same in plain egui - the result should be using `egui`'s default font.

The use case would be to change font properties without having to supply a custom font. To work around this, one can add a custom font, but not inserting it into into the font families.

This can be easily reproduced by commenting the whole content of the `setup` function in:
https://github.com/Nazariglez/notan/blob/develop/examples/egui_custom_font.rs

**Comment by Nazariglez** [comment]
Hey @woelper thanks for report this. I am trying to reproduce it but I don't understand pretty well what I need to do, if I comment the setup function, it still works.  Can you help me with it?

**Comment by woelper** [comment]
Thanks for looking into this! I'll take a look and put up a sample!

**Comment by woelper** [comment]
Sorry for not providing a better example to reproduce this. I forked and edited the example like this:
https://github.com/woelper/notan/blob/develop/examples/egui_custom_font.rs

This panics if run with `cargo run --example egui_custom_font --features egui`

Basically, this can be triggered with just 

```rust
let mut fonts = egui::FontDefinitions::default();
// Not creating a new font here as in the original example, just set the default
ctx.set_fonts(fonts);
```

Let me know if you need more info!
