### ISSUE TITLE
window is transparent, even if set to false

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#218]
after upgrading from 0.8 to 0.91, I can now see other windows in the background if I am displaying a texture with semi-transparent pixels.

I have tried adding `.transparent(false)` to my WindowConfig, but this does not change anything.

This is a window displaying a texture on top of this webpage:
![image](https://user-images.githubusercontent.com/3613791/215359332-02dc3201-48fe-438f-8d23-75c9b728ff53.png)

I am using 
```
draw.image(texture)
.blend_mode(BlendMode::NORMAL);
```
(This is on Linux/popOS)

**Comment by LedinecMing** [comment]
Having same problem

**Comment by Nazariglez** [comment]
I am talking with the people from `glutin` to see what will be a good approach to fix this. Meanwhile... I think that clearing the windows with a solid color when the frame starts will fix the issue. (I hope so). 

```
fn draw(gfx. &mut Graphics) {
    let mut draw = gfx.create_draw();
    draw.clear(Color::BLACK);
    // you can keep using here this draw instance to draw your stuff if you want
    gfx.render(&draw);
    
    // or maybe you want to do it in 2 passes, so after clearing the windows you can do your stuff here
    // 2 passes can work fine for an app like oculante, 1 pass is better for games to avoid extra draw calls 
}
```

**Comment by woelper** [comment]
Thank you so much!

**Comment by Nazariglez** [comment]
Anytime! Sorry for the inconveniences. `0.9.2` will be out today probably.
