### ISSUE TITLE
Wrong window size on linux mint

### ISSUE THREAD

**Issue by LedinecMing** [Nazariglez/notan#219]
gfx.device.size() gives different results when on linux or on windows(using wine) in setup function
attached first is linux, second is windows
![linux](https://user-images.githubusercontent.com/63245550/215580948-cc9c6499-5a58-4573-8860-dda1a187bbff.png)
![windows](https://user-images.githubusercontent.com/63245550/215580966-02e2829a-aed7-4d3a-904a-d2c6f9b74d5b.png)

**Comment by Nazariglez** [comment]
Hello, which one is the right one? Linux or Wine? Should the white line be there as in the first image, or not?

I tried to replicate this behavior but the setup method returns the same size that I pass in the config, no matter that I use `app.window().size()` o `gfx.size()`.

**Comment by LedinecMing** [comment]
> Hello, which one is the right one? Linux or Wine? Should the white line be there as in the first image, or not?
> 
> I tried to replicate this behavior but the setup method returns the same size that I pass in the config, no matter that I use `app.window().size()` o `gfx.size()`. 

White line means background is not same size as window size, it happens on linux.

**Comment by LedinecMing** [comment]
@Nazariglez So gfx.size() returns wrong size in a `setup` function, but later in `draw` it returns correct window size.

**Comment by Nazariglez** [comment]
hey @LedinecMing Can you try with this branch? https://github.com/Nazariglez/notan/tree/log/size and paste here all the logs? Thanks

**Comment by Nazariglez** [comment]
@LedinecMing are you using mint with wayland? We think that this issue could be related to https://github.com/Nazariglez/notan/issues/265 and https://github.com/rust-windowing/winit/issues/1446, I'll try to find a solution in the next few days/weeks if it's related.

**Comment by LedinecMing** [comment]
I will try soon, still X.

**Comment by LedinecMing** [comment]
@Nazariglez https://pastebin.com/t4pWVHj4 here is logs and a minimal reproduction code 
![image](https://github.com/Nazariglez/notan/assets/63245550/d1e1988e-04af-48e0-aaec-17c420460a34)

**Comment by Nazariglez** [comment]
This is weird, I do think that the changes made in the next version of winit will help, let's keep this on hold until then. 

Thanks!

**Comment by joseluis** [comment]
Hi there. I don't know if I'm experiencing similar issues. I come here from [a discord thread](https://discord.com/channels/1020682760844742666/1020688536611065926/1170420970733981717).

I made a simple example to showcase the problem:
```rust
use notan::{draw::*, init_with, prelude::*};

#[notan_main]
fn main() -> Result<(), String> {
    let win_config = WindowConfig::default()
        // .set_size(300, 300) // window pixel size would be auto-scaled by dpi==1.66
        .set_high_dpi(true) // doesn't seem to change anything
        .set_resizable(true);
    init_with(setup).add_config(win_config).add_config(DrawConfig).draw(draw).build()
}

fn setup(app: &mut App) {
    let window = app.window();
    let dpi = window.dpi();
    // here we scale back the window size to a REAL pixel size of 300x300x
    window.set_size(unscale(300, dpi), unscale(300, dpi));

    println!("dpi: {dpi}");
}

fn draw(app: &mut App, gfx: &mut Graphics) {
    let _dpi = app.window().dpi(); // == 1.66

    // FIX 1: this causes the square to render at the BOTTOM left:
    // gfx.set_size(unscale(100, _dpi), unscale(100, _dpi));
    
    // FIX 2: this causes the square to render 80 pixels over the BOTTOM left:
    // gfx.set_dpi(1.0);

    let mut draw = gfx.create_draw();
    draw.clear(Color::BLUE);

    // When not changing gfx's size or dpi this renders at the TOP left:
    draw.rect((0.0, 0.0), (100.0, 100.0));

    gfx.render(&draw);
}

/// Removes a `dpi` scaling factor from a `value` in pixels.
#[inline]
fn unscale(value: u32, dpi: f64) -> u32 { (value as f64 / dpi) as u32 }
```
![image](https://github.com/Nazariglez/notan/assets/5832068/429cb646-a89f-4e30-9af2-c6e379ae3f7f)

I'm using Linux Mint + XFCE.

Notan was detecting a dpi of 1.66..., which derived in these problems. But after updating my custom DPI settings in "Settings -> Appearance -> Fonts" from the 96 dpi by default to another value, and back, notan then reports a dpi of 1, which fixed my problems.

Additionally changing the DPI settings away from 96 dpi makes the gfx rendering on the y axis diverge by about 3.5 pixels per dpi point, so there maybe something there worth looking into.
