### ISSUE TITLE
Is it possible to get (keyboard) events when the window is not focused?

### ISSUE THREAD

**Issue by xanderjakeq** [Nazariglez/notan#235]
The default input events seem to only be detected when the window is focused. I want to listen to keyboard/mouse events even the window in unfocused. Is it possible to do that?

I saw this [device_query](https://docs.rs/device_query/1.1.2/device_query/index.html) crate, it can listen to keyboard events without needing a window. Is it possible to integrate this with notan?

**Comment by xanderjakeq** [comment]
`device_state.get_keys()` from `device_query` can be used within the update function of notan.

**Comment by Nazariglez** [comment]
Hello @xanderjakeq, thanks reaching out, if getting the keys on the update method works for you that's great! Another option could be create a custom plugin, but it will need more boilerplate.
