### ISSUE TITLE
Unresponsive window if using .vsync(true) on linux

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#243]
Hey, I hope you are well!
I am still gathering more information, but after what I believe was an operating system upgrade (PopOS) apps built with Notan now freeze at startup if `WindowConfig` sets vsync to true. I could reproduce this by running `cargo run --example window_config` in notan, and current and past versions of my image viewer Oculante stopped working. 
This could well be specific to my hardware and operating system, so please see this as very low priority unless this is caused by a library update which will become mainstream for more users. I will disable vsync on Linux for now and test with other hardware.

**Comment by woelper** [comment]
Sorry for the noise, but this seems very much like something related to my setup. I'll reopen if I have more relevant information.

**Comment by Nazariglez** [comment]
No worries, let us know if you need anything!
