### ISSUE TITLE
DrawTransform matrix multiplication possibly in wrong order

### ISSUE THREAD

**Issue by Olaroll** [Nazariglez/notan#248]
So I'm using the DrawTransform API like so:
```rust
draw.image(&tex)
    .scale(scale.x, scale.y)
    .translate(pos.x, pos.y);
```
In a case like that, I would expect for the scaling to be applied first, then the translation. Instead it's currently the opposite

In the transformation functions, it's multiplying the transformation matrix like so: `*self.matrix() = old * new`, but since multiplying transformations applies them from right to left, we get this reverse ordering.

Obviously changing this would be a breaking change, but I think it would be for the better in the end.

**Comment by Nazariglez** [comment]
Hey, this is a nice catch, 0.10 will probably contain breaking changes, so it's time to address something like this for sure. Thanks for the heads up!
