### ISSUE TITLE
Elaborate the nine slicing example. 

### ISSUE THREAD

**Issue by jayphur** [Nazariglez/notan#253]
I'm excited to see that notan has a nine slicing feature, however `examples/draw_nine_slice.rs` does not really explain how the feature works. (such as defining where the corner are on the image).

**Comment by Nazariglez** [comment]
Hello! The corners are calculated automatically by dividing the width and height of the image passed by 3. You can alter those parameters with the methods `top|bottom|right|left` to define how much of the image you want to use per size. 

https://docs.rs/notan/latest/notan/draw/struct.NineSlice.html
