### ISSUE TITLE
Mouse scrolling issue

### ISSUE THREAD

**Issue by devmeat** [Nazariglez/notan#267]
Having an odd problem with mouse scrolling. `app.mouse.wheel_delta.y` would only update when there is some kind of an event on the mouse. So I get this behavior where it would return 50 on mouse wheel scroll, but won't immediately reset to 0. It only resets to 0 when I use the mouse in any way.

I'm aware of listening for scrolling events via `fn event`, but I would like to avoid doing that since everything else is easily accessible using `app.mouse`. But sadly it doesn't have a scrolling equivalent.

May I request adding `app.mouse.was_scrolled() -> f32`?

```rust
use notan::draw::*;
use notan::log;
use notan::prelude::*;
use notan::math::{vec2, Vec2};

#[derive(AppState)]
pub struct GameState;

#[notan_main]
fn main() -> Result<(), String> {
    let window_config = WindowConfig::new()
        .size(200, 200);

    notan::init_with(init)
        .add_config(window_config)
        .update(update)
        .build()
}

fn init() -> GameState {
    GameState {}
}

fn update(app: &mut App, state: &mut GameState) {
    log::info!("Scroll: {0}", app.mouse.wheel_delta.y);
}
```

**Comment by Nazariglez** [comment]
Hey @devmeat, this should be fixed on the `develop` branch, and it will be out on crates.io on with the next `0.10` version. Feel free to reopen the ticket if something feels wrong! 

Thanks for reporting it.

**Comment by devmeat** [comment]
Hi @Nazariglez, thank you for fixing this issue. Unfortunately I found another issue. 
When you move the mouse in any direction while scrolling the mouse wheel, it seems to flip the value on `app.mouse.wheel_delta.y`

```rust
if app.mouse.is_scrolling() {
  if app.mouse.wheel_delta.y > 0.0 {
         state.camera.scale += ZOOM_SPEED;
      } else {
          state.camera.scale -= ZOOM_SPEED;
      }
    }
```
