### ISSUE TITLE
`notan_graphics` depends on `image` when feature `texture_to_file` is disabled

### ISSUE THREAD

**Issue by excalibreak** [Nazariglez/notan#271]
# Problems
In `notan_graphics`, `image` is only used in `to_file.rs` which is tied to `texture_to_file` feature, but `image` is still a dependency when `texture_to_file` is disabled.

`jpeg` feature is used even though `notan_graphics` only encodes pngs.

# Possible Solution
Add `image` as a dependency to `notan_graphics` only when feature `texture_to_file` is enabled. Disable `jpeg` feature from `image`. Even better, you can replace `image` with `png` or `spng` for encoding pngs.

**Comment by Nazariglez** [comment]
Hello! Thanks for taking the time to check this. I'm inclined to the first solution, using image only when `texture_to_file` is enabled. I am thinking about a big refactor soon and I'll reevaluate it soon. Though if you think that using `png` is a better solution for your case I am open to PRs!

Feel free to reopen. Thanks!
