### ISSUE TITLE
Colors on 0.10.0 are much darker than on 0.9.5

### ISSUE THREAD

**Issue by jonatino** [Nazariglez/notan#273]
Hello! I upgraded to 0.10.0 (latest commit) as part of adding https://github.com/Nazariglez/notan/pull/272

I added it as part of a fix for another repo, an image editor https://github.com/woelper/oculante/pull/201

After using notan 0.10.0 I noticed that the images in the viewer look much different.

Top is old notan 0.9.5, bottom is new notan 0.10.0.

![image](https://github.com/Nazariglez/notan/assets/1808569/2afc987e-7f56-4f1c-92e3-855096d7601c)

**Comment by woelper** [comment]
It looks even the text on the title bar is darker, or is this because of a window shadow? I am trying to see if it is only the image or if other things (UI) are affected too

**Comment by jonatino** [comment]
> It looks even the text on the title bar is darker, or is this because of a window shadow? I am trying to see if it is only the image or if other things (UI) are affected too

Just seems to be the image itself. UI elements and colors are identical across versions.

**Comment by Nazariglez** [comment]
Hey, this is weird, maybe a srgb issue? Can I use the branch https://github.com/woelper/oculante/pull/201 to test it? it that branch the one that fails? About the image, does it happen with any image or only that?

**Comment by jonatino** [comment]
> Hey, this is weird, maybe a srgb issue? Can I use the branch [woelper/oculante#201](https://github.com/woelper/oculante/pull/201) to test it? it that branch the one that fails? About the image, does it happen with any image or only that?

Yeah use this branch https://github.com/woelper/oculante/pull/201 with notan 0.10.

It happened with every image I opened.

**Comment by Nazariglez** [comment]
Hey, I am having some busy days lately, I'll take a look to this soon. Thanks!

**Comment by devmeat** [comment]
@jonatino  Mind adding a snippet to replicate this issue?

**Comment by Nazariglez** [comment]
I got this fixed on the oculante source, is an issue with Srgb and the default pipeline used on the draw manager. I need to cleanup the code a little and is quite late here now, so I'll do it in the next few days and I'll send you a PR.

**Comment by Nazariglez** [comment]
Done https://github.com/jonatino/oculante/pull/1. We can talk on that PR if something else is required. Feel free to reopen the issue if you need to. Thanks @devmeat for offering to take a look into this.
