### ISSUE TITLE
Let's talk about the future of Notan - Looking for maintainers

### ISSUE THREAD

**Issue by Nazariglez** [Nazariglez/notan#277]
Hello awesome people! I want to talk a little about the future of Notan. 

Let's start by sharing that I am looking for maintainers. Notan v10 is about to be ready. There are some issues open yet to be solved (#276, #273, #267, #249), but I do think they are not a big deal (at least I hope so). 

## Why am I looking for maintainers? 

In recent months, I've noticed that my free time to dedicate to Notan has drastically decreased. I've reached a point where I find it hard to justify spending my limited spare time on the project, especially when it currently doesn't provide me any rewards nor meet the objectives I initially set for it.

These objectives were mainly two:
* Act as a foundation for my games: Over the course of the 4-year project, 1.5 years of which have been open-source, I have developed a total of zero games. All my free time is spent fixing, improving, or providing support for Notan.
* Serve as a foundation for other community projects, abstracting code to create apps on various platforms (web, desktop, mobile?) in such a way that changing backends while maintaining the app's API is easy: This has not been achieved, as projects like egui, iced, any game engine out there, and many others prefer to create their own backends for each platform.

I believe Notan is in a very good state for use, and I myself am using it to develop a game that I hope will land on Steam at some point.  However, there are certain challenges within the project that need substantial improvement. I must admit, some of these issues have been particularly persistent and draining to address:
* Mobile support is challenging.
* Egui integration could be better (dpi issues? blurry at times?).
* There are srgb issues with the 2D API.
* The async assets loading API is too strict.
* GFX extensions do not allow the use of other extensions (i.e., egui paint cannot use our draw2d API).
* The Rust community has made a definitive shift from OpenGL to WGPU
* Support for exotic Linux distros, Wayland, etc...
* Text/font rendering/layout
* Etc...

Improving all these aspects requires time - not just time to develop solutions, but time to experiment and think of good solutions that align with Rust and the project. Because, yes... sometimes Rust can be a pain, forcing us to rethink and refactor a large portion of a project, and this can be exhausting... And I would like to focus on making games or more productive projects than just consuming all my spare time supporting features I do not really use.

I'm currently looking for maintainers to help improve Notan, as my time has been limited. I appreciate your understanding and hope to see the project grow and evolve even as my role changes.

In recent weeks, I've been experimenting with a more modular structure where various elements like windows, graphics, sounds, etc., can be injected as plugins. While Notan already supports this, the backend still expects windows and input to be available. The result of these experiments is a considerable change in the API and approach, necessitating further adjustments across all systems (windows, inputs, graphics, etc.). I acknowledge that this level of overhaul is something I'm not ready to commit to at this time. Moreover, I anticipate that such a radical transformation, essentially making it a new project, might not sit well with the community.

I'd like the project to continue. I know there are people who appreciate Notan's approach and projects that use it as a base. I am really grateful for the community we've built, and the awesome users Notan has. That's why I'm seeking new maintainers to help the project continue.

Please accept my apologies in advance - this post is a bit of a "thinking out loud" moment. I'd like to discuss this with the community, hear your opinions, and see if anyone wants to step forward. Thank you!

**Comment by Nazariglez** [comment]
Hello! Sorry for taking some time to answer here. 

Let me try to give some context. My main issue with notan right now has nothing to do with notan itself but with me. Sometimes I only see the bad side of my project and I feel the urge to fix it, and if I have no time then I get frustrated. I feel a bit burned out because it's hard to achieve goals in this crazy world that we have where we have day jobs, side projects, etc...

However, notan is right in the best state ever, it's stable, useful, and kind of battle-tested. So, i think this is good enough for now?

I have been playing a little bit with different techs and experimenting with patterns and wgpu, etc... Just having some fun. And I think I have something in the oven that can work as backend for notan that will resolve (at least):
* Mobile support (I tested iOS, my guess is that android should works at not be too difficult to impl).
* More flexible asset loader (opinionated, maybe I just keep the current one)
* WGPU support.
* Remove `glsl_to_spirv` (wgpu backend uses `naga` no more c-toolchain deps).

This was my playground: https://github.com/Nazariglez/gamekit/tree/f/rt2/examples. And the idea is to migrate to notan everything that makes sense while keeping the notan's API the same (kind of), or at least avoiding big changes.

I am keeping a few weeks (probably a month or so) away from side projects that require coding because I want to recharge my batteries. And I hope to come back to start working on the new backend before the end of the year. 

I'm going to close this issue because I believe it gives the wrong impression that the project is abandoned.

Thank you so much!

**Comment by woelper** [comment]
Let me just say a very big **thank you** for all your work. For me, `notan` is the best Rust "Multimedia" or general purpose engine available. Apart from updating dependencies like egui from time to time (which also others can do, and I hope I will find time to contribute) it is damn near perfect.

I too probably work too much on side projects, and I understand the challenge of doing so. Some people might call open source contributors like you crazy for working for free on side projects like `notan` - with a day job, friends and family at the side. Why put up with so much stress? I hope you know that some people really value your work, admire the quality of it and it ends up making a lot of people happier, be it direct or indirect users. I think it is worth it, but please take care and try to find a balance that works for you.
