### ISSUE TITLE
Please remove the dependency on the crate glsl-to-spirv because it is unmaintained and abandoned

### ISSUE THREAD

**Issue by yurivict** [Nazariglez/notan#287]
See [here](https://github.com/vulkano-rs/vulkano/issues/2318#issuecomment-1706042336).

**Comment by Nazariglez** [comment]
Hi @yurivict, alternatives are still not ideal. Only shaderc will take quite a few minutes to compile in the first compilation or after cargo clean. And Naga does not support quite good yet glsl as input. 

Ideal scenario will be using naga with wgsl, but that will require a lot of changes across the API, and I am not capable to fo that really get now fue time restrictions. But I am open to review and guide any PR if somebody is willing to put the work on it. 

As alternative, you can disable glsl to spirv and enable shaderc compilation using feature flags in your cargo.toml

**Comment by yurivict** [comment]
I wasn't able to build https://github.com/woelper/oculante because it used notan and glsl-to-spirv fails to build.

I guess I would just wait until this problem is resolved.

**Comment by Nazariglez** [comment]
I see, then it's an easy solution, we can add `shaderc` as a feature flag on oculante too. I am leaving there a comment.
