### ISSUE TITLE
Error: "extension to create ES context with wgl is not present"

### ISSUE THREAD

**Issue by mantasarm** [Nazariglez/notan#289]
With the `0.10.0` version of notan I get the error `Error: "extension to create ES context with wgl is not present"`. The program successfully compiles however it fails with the previously mentioned error.
![image](https://github.com/Nazariglez/notan/assets/34283640/56cb7c84-6748-44e8-8b9e-bda252e33b7a)

My machine is a Mac with an AMD card. It runs windows 10 with dual boot.
I had this error before in notan version `0.9.2` I believe. However the owner Nazariglez released a patch that fixed the issue. But now it for some reason it reappeared. Would really appreciate some help with this. I don't want to move away from notan.

The patch from last time: https://github.com/Nazariglez/notan/pull/223

**Comment by mantasarm** [comment]
I have been doing some testing myself, notan uses glutin version `0.30.8` and the provided examples of that glutin version compile just fine on my machine. It seems there's something wrong with how we get the glutin context.

**Comment by Nazariglez** [comment]
Hey @mantasarm, the error is only on window? I'll try to check it in the next few days to see if I can see what's going on.

**Comment by mantasarm** [comment]
Hey, so the error occurs in here [https://github.com/Nazariglez/notan/blob/develop/crates/notan_winit/src/gl_manager.rs](url) where the `window` and `gl_config` is gotten. If I replace this part with how the glutin repository creates the `window` and `gl_config` [https://github.com/rust-windowing/glutin/blob/master/glutin_examples/src/lib.rs](url), then it works. That's all I have tried out.

**Comment by Nazariglez** [comment]
Hey, sorry I explained poorly myself, I mean, is it only happening on the Window OS? Mac is not affected by this?

**Comment by mantasarm** [comment]
Ohhh. Yeah, so I just tried out latest version of notan on my MacOS boot and seems to working just fine. It seems only my windows OS is affected.

**Comment by mantasarm** [comment]
Interesting update - If I set the multisampling to any other number than zero, then the window opens. But if disable multisampling (set it to 0) then the error occurs.
