### ISSUE TITLE
readme images hosted in gfycat.com no longer exist

### ISSUE THREAD

**Issue by joseluis** [Nazariglez/notan#295]
gfycat.com shutdown in september, so the readme images should be linked to somewhere else

**Comment by Nazariglez** [comment]
Agh!  I need to find the images because I am not sure where I have them on my local devices. If I cannot find them I'll create new ones. 

Thanks for the heads up

**Comment by MrAdhit** [comment]
> Agh! I need to find the images because I am not sure where I have them on my local devices. If I cannot find them I'll create new ones.
> 
> Thanks for the heads up

You can get the images from the Wayback Machine
https://web.archive.org/web/20220829110238/https://github.com/Nazariglez/notan

**Comment by joseluis** [comment]
That's good! I've linked them here directly for convenience:
![1](https://web.archive.org/web/20220829110238im_/https://camo.githubusercontent.com/6c3b9953ca4860021443f5baa34d49cbe97c7eeb1e0fd2266ba8dc9dab87b959/68747470733a2f2f7468756d62732e6766796361742e636f6d2f486f727269626c65466561726c657373496e76697369626c657261696c2d736d616c6c2e676966)
![2](https://web.archive.org/web/20220829110238im_/https://camo.githubusercontent.com/a585332847eb38ba794bace4507259bb838bf191bf6fdeff1d0ee1127ccc0da2/68747470733a2f2f7468756d62732e6766796361742e636f6d2f477265676172696f757347726565647943726f636f64696c652d736d616c6c2e676966)
![3](https://web.archive.org/web/20220829110243im_/https://camo.githubusercontent.com/ca55e9dae03a226a9b01e274c4622bec62f8acef99dc72f25e6d023e6a59d8f9/68747470733a2f2f7468756d62732e6766796361742e636f6d2f5765616c7468795365706172617465466f78686f756e642d736d616c6c2e676966)
![4](https://web.archive.org/web/20220829110238im_/https://camo.githubusercontent.com/611d82c9aea5fc98db883cf1b65f1d5ab88b76c57cb30732da7024657a4ec02a/68747470733a2f2f7468756d62732e6766796361742e636f6d2f496c6c66617465644d69736775696465644c6963652d736d616c6c2e676966)
