### ISSUE TITLE
Possibility to set app_id

### ISSUE THREAD

**Issue by martinlindhe** [Nazariglez/notan#304]
app_id is a wayland property which is a string identifier. x11 apps have a similar property called `class`.

It would be helpful to be able to set this value using the notan api.

winit has a method that wraps the above behavior, called [with_name](https://docs.rs/winit/latest/winit/window/struct.WindowBuilder.html#method.with_name-1)

Currently on a sway setup (`swaymsg -t get_tree`), running `cargo run --release --example draw_image` 
```
#11: con "~/.config/sway/config - Sublime Text" (xdg_shell, pid: 1998, app_id: "subl")
#13: con "Issues · Nazariglez/notan — Mozilla Firefox" (xdg_shell, pid: 1922, app_id: "firefox")
#2052: con "Notan App" (xdg_shell, pid: 1248803)
```

**Comment by Nazariglez** [comment]
This is interesting, do you think it makes sense to create this id automatically from the app's title? Like from "Notan App" it could be "notan_app". Though i am not sure if it makes sense because the title can change while my guess is that the app_id should remain the same all time.

**Comment by martinlindhe** [comment]
> This is interesting, do you think it makes sense to create this id automatically from the app's title? Like from "Notan App" it could be "notan_app". Though I am not sure if it makes sense because the title can change while my guess is that the app_id should remain the same all time.

The app_id should be a unique non-changing identifier, so I think it should be a separate function. (And don't fill it with a default value, its better left unset rather than multiple applications sharing the same app_id).

**Comment by Nazariglez** [comment]
I made this PR: https://github.com/Nazariglez/notan/pull/306. 

I think it's useful having this because I can use it also as canvas_id for the web target, so the functionality was just there only that the native backend did not use it. Winit has enabled by default the features `X11` and `Wayland` for UNIX so I am not checking which one is the app running on, I am just assuming that the feature is enabled. I tried in X11 without issues. It would be great to see if it works on wayland.

**Comment by martinlindhe** [comment]
Verified PR #306 works on wayland.

Without changes to the test app (oculante) , app_id is "notan_app":

    #75: con "Oculante | 0.8.6" (xdg_shell, pid: 77191, app_id: "notan_app")

With
```rust
WindowConfig::new().set_app_id("oculante")
```
we get: 

    #77: con "Oculante | 0.8.6" (xdg_shell, pid: 77746, app_id: "oculante")

**Comment by Nazariglez** [comment]
So nice, thank you for the help!
