### ISSUE TITLE
Blurry text / low-dpi egui since v0.12.0

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#315]
Since `v.0.12.0` the egui UI / text has become blurry. This can be reproduced by running `cargo run --example egui_basic --features egui` on the different releases and comparing the output.

Left is `v.0.12.0`, right is `v.0.11.0`.
<img width="402" alt="image" src="https://github.com/Nazariglez/notan/assets/3613791/e3e95a80-975f-40b5-a08d-25b0ced5f8bb">

Maybe related to #313?

Downstream issue in Oculante is [here](https://github.com/woelper/oculante/issues/277).

**Comment by mantasarm** [comment]
Having the same issue. For me it is even worse - the text is basically unreadable. I did however found a work around that fixes the problem. Setting the `egui` pixel density to the dpi.
`ctx.set_pixels_per_point(app.window().dpi() as f32);`
