### ISSUE TITLE
Window bash scripts (powershell)

### ISSUE THREAD

**Issue by Nazariglez** [Nazariglez/notan#319]
I think that we should try to find a way to avoid the duplication of the scripts inside the [scripts folder](https://github.com/Nazariglez/notan/tree/develop/scripts). I am not a big Windows user, I always work under UNIX (macOS and sometimes Linux), and I only test the examples or projects manually on Windows from time to time, that's why I did not think about porting the scripts to Windows (as @Rzial [did here](https://github.com/Nazariglez/notan/pull/314)). 

I worry that the window's script gets outdated fast, mainly because I may forget to update them along with the bash scripts. So I would like to explore other options, maybe we should get rid of the bash/ps scripts and use a common language in both systems like Python? 

It seems that projects like [tauri](https://github.com/tauri-apps/tauri) use Bash and PowerShell scripts as we do now, others like [bevy](https://github.com/bevyengine/bevy) only use bash, while [egui](https://github.com/emilk/egui) uses a mix of bash and python scripts for different things.

What do you think @Rzial? I would like to hear opinions from Window's users. Thanks!

**Comment by Rzial** [comment]
Seems something legit, I can take a look on it.

Just to add some things to the table what do you think about "rust-on-rust" a solution?
Maybe using the 'cargo' crate to do something alimented by a toml that allows to do this.

I'm just thinking out loud.

**Comment by Nazariglez** [comment]
> Just to add some things to the table what do you think about a "rust-on-rust" solution?
Maybe using the 'cargo' crate to do something alimented by a toml that allows to do this.

Do you have any candidates in mind? I was looking at [cargo script]() but it seems outdated and it requires the installation of an additional plugin. Then [xshell]() looks interesting too, however, I am not sure how we can execute the scripts, do we need a new package to run the scripts? 

I am inclined towards the frictionless path, if we can avoid requiring more deps and is easy to execute I am fine. That's why I thought of python because is pretty similar to bash and is probably installed already on most machines. The downside is that the scripts are in another language yeah. But I am open to suggestions ofc!

**Comment by StarLing-sketch** [comment]
Git Bash https://git-scm.com/downloads

**Comment by Rzial** [comment]
While Git Bash could be handy using the original sh files I would rather prefer to have an approach that doesnt add more dependencies to the current stack.

Current project dependencies can manage this issue.

I'm still working on it but didn't found time to prepare and present a proper PR 😅

**Comment by Nazariglez** [comment]
Anything that makes window's user life easier makes sense to me. I am open to anything. What are your thoughts about https://github.com/matklad/cargo-xtask? it seems to be used on projects like zellij, rust-analyzer, and even cargo itself! 

It looks very interesting.
