### ISSUE TITLE
How to use draw + egui?

### ISSUE THREAD

**Issue by Liburia** [Nazariglez/notan#333]
I want to draw some basic shapes and then have UI on top of them.

**Comment by Liburia** [comment]
All of the examples have only egui plugin in the drawing stage. I want to draw shapes using notan, and also have egui on top of that.

**Comment by woelper** [comment]
> All of the examples have only egui plugin in the drawing stage. I want to draw shapes using notan, and also have egui on top of that.

Doesn't the `egui_shape_widget` do exactly that?

**Comment by Liburia** [comment]
I apologize. I have no idea how I missed that one.
