### ISSUE TITLE
File drop event

### ISSUE THREAD

**Issue by woelper** [Nazariglez/notan#75]
Hi there, and first thanks so much for this library!
I was searching a lot for a small and light multimedia / game library with possible egui integration - this seems to have it all!
I am currently planning to rewrite a [small image viewer I wrote](https://github.com/woelper/oculante) with notan. It seems the only thing I am missing is an event in case the window receives a dropped file. Since you are using `winit` would this be something you would consider adding or accepting a PR?
Here are the winit events: [link](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html)

Thanks!

**Comment by Nazariglez** [comment]
Hey, your project looks really cool.

 I added drag&drop support already on the develop branch, it will be available on the next version in a few days (I hope). If wait doesn't work for you, you can use notan from the repository, and if you plan to use egui I would suggest using the branch `f/egui` where I'm working to improve the integration with it adding some missing features and fixing other issues.

To use the drag&drop feature you need to enable the feature on your Cargo.toml (["drop_files"]). It only works on native at the moment, I need more time to think about the right way to implement this on the web backend. 

I'll keep this issue open until it's fully implemented in all the backends. 

I'm trying to gather all the feedback I can, if you see something missing, not working or that feels wrong let me know!

Thanks!

**Comment by woelper** [comment]
Thank you so much, this sounds amazing!

Also many thanks for the example. I can totally understand that this should be optional or even left out in a web context. 
Depending on how I progress I will give the branch a try!

Thanks again, and I'll let you know if I encounter anything else!

**Comment by Nazariglez** [comment]
PR #76 is merged now on `f/egui`. It adds support for drag and drop and loading dropped files on native and web backends. It will arrive at crates.io on the next `0.2.0` version. 

I think that this is resolved right now. Feel free to reopen the issue or a new one if something feels weird. 

Thanks!

**Comment by woelper** [comment]
Thank you very much!
