### ISSUE TITLE
Add an option to execute the app's inner loop only after an event/input 

### ISSUE THREAD

**Issue by Nazariglez** [Nazariglez/notan#81]
Related #77. This is especially important for applications that need to reduce the CPU use avoiding the iteration when there is nothing new on the screen to draw.

**Comment by Nazariglez** [comment]
Hey @woelper moving the talk here.

>  discovered that enabling FpsPlugin with vsync() causes CPU usage to go up again to previous levels, but maybe that is expected.

This should not be the case, I'll check it, thanks for the report. 

>  Using vsync() helps a lot and drops CPU usage from 60%/app and 50%/Xorg to around 6%/app, which is way better

Glad that it worked!

>  Using vsync() helps a lot and drops CPU usage from 60%/app and 50%/Xorg to around 6%/app, which is way better

Nice trick! It makes sense if the changes on your application always come from egui. I copied your trick and applied it to the egui_shape_widget example. 

I'm working on the branch `f/lazy`, it does work with the native backend already. Check https://github.com/Nazariglez/notan/blob/f/lazy/examples/egui_shape_widget.rs#L38-L39. Using `.lazy_loop()` with `.vsync()` should reduce to 0% the CPU when there is no input, and up to "normal" levels of CPU when something is happening. 

Just as a side note, if your app contains animations that don't depend on the user's input this mode will not work for you because there is no draw if there is no user's input. I added `app.window().request_frame()` as a workaround to force the next frame, you can call this while you're animating. For example, using egui, it's good to call it when egui needs repaint, this always will call 1 frame more than needed but if egui is animating something it will keep drawing until the animation is over. Check https://github.com/Nazariglez/notan/blob/f/lazy/examples/egui_demo.rs#L29-L35 

If none of this works for your case, there is another option: https://crates.io/crates/spin_sleep. We can create a plugin using that crate for the native backend, it will block the execution thread until the time passed.

**Comment by Nazariglez** [comment]
This is already on `develop`.

**Comment by woelper** [comment]
Thanks so much, I'll give it a try!

**Comment by woelper** [comment]
Thanks again, this is awesome. I tried `lazy_loop()` without `vsync()` for fun, and it gave absolutely lag-free scrolling an panning (vsync was feeling a bit sluggish) while having almost no CPU usage when idle. Great job!

**Comment by Nazariglez** [comment]
Nice, glad that it worked. Version `0.2.0` is already on crates.io. I think that it's safer to use it from there than from the `develop` branch which can be broken without notice at any moment :P 

Thank you so much for your help and feedback!
