### ISSUE TITLE
Notan won't build

### ISSUE THREAD

**Issue by getzen** [Nazariglez/notan#88]
I created a new project with cargo and added Notan as a dependency to Cargo.toml, but I get an error message upon trying to build the project. I tried both 0.2.0 and 0.2.1. I have an iMac.

...
   Compiling lyon_path v0.17.7
   Compiling glsl-to-spirv v0.1.7
error: failed to run custom build command for `glsl-to-spirv v0.1.7`

Caused by:
  process didn't exit successfully: `<PATH DELETED> .../notan/target/debug/build/glsl-to-spirv-86dc8c8efd4cd674/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build/glslangValidator.exe
  CMAKE_TOOLCHAIN_FILE_x86_64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_x86_64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-apple-darwin = None
  CMAKE_GENERATOR_x86_64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-apple-darwin = None
  CMAKE_PREFIX_PATH_x86_64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-apple-darwin = None
  CMAKE_x86_64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/jim/.cargo/registry/src/github.com-1ecc6299db9ec823/glsl-to-spirv-0.1.7/glslang" "-DCMAKE_INSTALL_PREFIX=/<PATH DELETED>/notan/target/debug/build/glsl-to-spirv-63c20502889b8cb9/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /Users/jim/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Nazariglez** [comment]
Hi! Notan uses a macro to compile the shaders at build time, this macro uses glsl_to_spriv and it requires to have installed in the system `cmake`. You can install it using `brew install cmake` if you have `brew` in your system, or manually following the steps from `https://cmake.org/install/`.

This is one of the pain points on notan, I hope to fix it by moving the shader compilation to [naga](https://crates.io/crates/naga) soon. 

Let me know if installing `cmake` works for you.

**Comment by getzen** [comment]
Thanks for the explanation. I don't have cmake installed, so I'm sure that's the problem. I'm experimenting with different graphics libraries. If I circle back to Notan, I'll install cmake and give it another try.

**Comment by Nazariglez** [comment]
Nice, rust has some nice libraries, if you're looking for something similar to notan, check https://github.com/not-fl3/egui-miniquad. Have fun!

I'm closing the issue but feel free to reopen if you need it.
