### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by yzn-h** [Nazariglez/notan#95]
getting the Error: "Couldn't find any pixel format that matches the criteria" on wayland.

**Comment by Nazariglez** [comment]
Can you give me more info about it? Is this a panic? Can you run it with `RUST_BACKTRACE=1`?

**Comment by yzn-h** [comment]
running the bunnymark example with RUST_BACKTRACE=1 

`Error: "Couldn't find any pixel format that matches the criteria."`

![image](https://user-images.githubusercontent.com/63852512/167280060-99be368b-d666-4c07-a54b-c8c5ea09a982.png)

**Comment by yzn-h** [comment]
this is with the input mouse example
![image](https://user-images.githubusercontent.com/63852512/167280098-b55c8b6a-a78a-4b88-bbda-e0e287f63f12.png)

**Comment by Nazariglez** [comment]
I have done some research and this seems to be an issue with the drivers wayland+mesa. Are you using mesa? My machi has xorg+nvidia so I cannot test this easily. I did a little update on the gl context builder, can you try again draw_bunnymark  to see if it works? Thanks

**Comment by yzn-h** [comment]
on fedora 36 it works 🎉

**Comment by Nazariglez** [comment]
Great, thanks!
