### ISSUE TITLE
Rotate text?

### ISSUE THREAD

**Issue by getzen** [Nazariglez/notan#98]
Is there a way to rotate text? I tried something like:

draw.text(&font, "Hello World").rotate_degrees(45.0);

but the result was unexpected. The text letters are drawn upright, but the baseline follows a slant. It's odd

<img width="349" alt="Screen Shot 2022-05-17 at 3 22 41 PM" src="https://user-images.githubusercontent.com/2192842/168893567-cfd1c8d0-d285-497f-a0de-c4f6ce44abd9.png">
.

**Comment by Nazariglez** [comment]
This looks like a bug, I should add a demo with transformed text to see if this fails. Do you know if this happen with the raw text API? 

Thanks for the report. I'll check it soon.

**Comment by getzen** [comment]
Are you referring to the API used by the glyph_hello_raw example? If so, I cannot get that example to build. The compiler says, "could not find `glyph` in `notan`" and "use of undeclared crate or module `notan_glyph`". I don't know how to solve that.

**Comment by Nazariglez** [comment]
I saw the bug, and I know why it's happening, still not sure how to fix it without a deep rewrite of the text draw API, so I need more time to investigate it. 

Thanks for the report!

PS: Its happening with `glyph_hello_raw` too, you should be able to run the example with ` cargo run --example glyph_hello_raw --features=glyph`
