### ISSUE TITLE
Is there a way to change the pointer to a custom png?

### ISSUE THREAD

**Issue by xdimi** [Nazariglez/notan#99]

**Comment by Nazariglez** [comment]
Do you have an example of what you want to achieve? I am not sure if I understand you.

**Comment by xdimi** [comment]
Sorry, I mean like, a certain command you can use to a file in the assets folder that sets the cursor to that image.

**Comment by Nazariglez** [comment]
Oh, I see, Yes! you can change the cursor with `app.window().set_cursor(CursorIcon::None)`, you have the available cursors here: https://docs.rs/notan/latest/notan/prelude/enum.CursorIcon.html.

If you want a custom png you should hide the system cursor with `CursorIcon::None`, load the texture you want to use and just draw it on the mouse position, check this simple example:

```
use notan::draw::*;
use notan::prelude::*;

#[derive(AppState)]
struct State {
    img: Texture,
}

#[notan_main]
fn main() -> Result<(), String> {
    notan::init_with(init)
        .add_config(DrawConfig)
        .draw(draw)
        .build()
}

fn init(gfx: &mut Graphics) -> State {
    let texture = gfx
        .create_texture()
        .from_image(include_bytes!("my_image.png"))
        .build()
        .unwrap();
    State { img: texture }
}

fn draw(app: &mut App, gfx: &mut Graphics, state: &mut State) {
    let mut draw = gfx.create_draw();
    draw.clear(Color::BLACK);
    draw.image(&state.img).position(app.mouse.x, app.mouse.y);
    gfx.render(&draw);
}
```
Let me know how it goes!

**Comment by xdimi** [comment]
Thank you! That is what I was looking for.
